:hardbreaks:
== [aqua]#9. IMPLEMENTACIÓ#

=== [aqua]#9.1. GITLAB#
https://gitlab.com/grup48254144/gamedex

=== [aqua]#9.2. JUSTIFICACIO DE DECISIONS#

** RF30 “Afegir comentari” i RF41 “Afegir videojoc a la biblioteca” han estat fusionats. Els comentaris formen part de la relació entre videojoc i usuari, i per tant els emmagatzemem en la relació “Library”/”Biblioteca”, com a atributs. 

** L’usuari inicia sessió amb el nom d’usuari i la contrasenya. El correu electrònic l’hem destinat només per a validar l’usuari a l’hora de recuperar la contrasenya. 

** En el requisit funcional 08 “Llistar usuaris”, es demana que sigui l’administrador qui pugui visualitzar una llista de tots els usuaris. Nosaltres hem decidit que per a la nostra aplicació era més convenient que tots els usuaris puguin accedir a la llista de tots els usuaris per a poder visualitzar els seus perfils. No obstant, en la pantalla d’usuaris, hi ha algunes funcions que només estan disponibles per a l’administrador, com ara el botó de validar. 

** Per conveniència, tots els usuaris poden accedir a un filtre a la pàgina d’usuaris per a poder filtrar-los per username. 

** Tots els usuaris poden accedir a visualitzar els perfils dels altres usuaris.

** Hem afegit un RF41, en el qual un usuari pot afegir qualsevol videojoc que hagi estat validat a la seva biblioteca.

** Tots els usuaris poden accedir a la seva biblioteca per a veure els videojocs afegits.

** En l’RF34 “(RF34) Eliminar comentaris”, l’usuari que ha posat el comentari també pot esborrar el seu propi comentari.

** Hem decidit que pots guardar un videojoc a la teva biblioteca però sense puntuació ni comentari, per tant hem post l’estat default en “want to play” i aquests comentaris no es llisten en la pàgina de veure videojocs. 

** Quan es va parlar de la implementació de seguretat per a l’aplicació, se’ns va dir que no feia falta fer seguretat, només l’autenticació i fer algún tipus d’encriptació per a la contrasenya, així que hem fet justament això. Per a la recuperació de la contrasenya, hem fet un sistema on en clicar el botó “Forgot your password?”, et portés a una pantalla on l’usuari introdueix el seu nom d’usuari i el correu electrònic i el sistema verifica que existeixi aquest usuari i que el correu electrònic sigui el correcte, aleshores surt un missatge avisant que s’ha canviat la contrasenya, se li mostra per pantalla la propia contrasenya  i se li demana clicar un botó per a confirmar que s’ha llegit.


=== [aqua]#9.3. LLISTAT DE FUNCIONALITATS FINALITZADES#

** (RF01) Login Usuari

** (RF02) Registre Usuari

** (RF45) Registre d’administrador

** (RF03) Recuperar contrasenya

** (RF04) Editar perfil usuari

** (RF48) Consultar perfil d’usuari

** (RF05) Logout

** (RF06) Validar Usuaris

** (RF07) Eliminar usuari

** (RF08) Llistar usuaris

** (RF09) Modificar usuaris

** (RF44) Filtre d’usuaris

** (RF46) Consultar usuari

** (RF10) Crear categoria

** (RF11) Llistar categories:

** (RF12) Filtrar per categoria

** (RF13) Consultar categoria

** (RF14) Modificar categoria

** (RF15) Eliminar categoria

** (RF16) Filtrar Videojocs per Categories

** (RF20) Afegir videojoc

** (RF21) Llistar videojocs

** (RF22) Filtrar videojocs

** (RF24) Consultar videojoc

** (RF25) Modificar videojoc

** (RF26) Eliminar videojoc

** (RF40) Validar proposta de videojocs

** (RF41) Afegir videojoc a biblioteca personal

** (RF42) Modificar videojoc a la biblioteca personal

** (RF43) Eliminar videojoc de la biblioteca personal

** (RF47) Consultar biblioteca personal

** (RF30) Afegir comentaris

** (RF33) Visualitzar puntuació mitjana

** (RF34) Eliminar comentaris


=== [aqua]#9.4. LLISTAT D'INCIDENCIES#

==== [aqua]#9.4.1. MARIO#

En el meu cas no he tingut gaires incidències, tot i això, alguns petits problemes sí que he trobat al llarg del projecte. En primer lloc, he trobat dificultats a fer les pantalles amb android studio, ja que tot i que no era un procés gaire difícil, al començament no quedava tot com m’agradava, però després vaig aprendre a fer millor les pantalles. També vaig trobar moltes dificultats amb les imatges perquè no sabíem com gestionar correctament les imatges i amb molt de temps i de recerca a internet vaig aconseguir que funcionessin com volíem. Per últim, l’API va costar molt de gestionar al començament, ja que els exemples de connexió amb API que havíem fet a classe eren molt més senzills que el que es requeria al projecte.

==== [aqua]#9.4.2. ANNA#
Aquest projecte ha estat tot un repte, doncs no he pogut treballar des de l’institut. Quan vam començar el segon Sprint i vam haver de començar a provar funcionalitats en l’emulador d’Android Studio, ja no vaig poder continuar fent servir el portàtil per a fer feina i per tant vaig haver de dedicar-li el doble d’hores, doncs vaig haver de fer tota la meva feina a casa. També vaig tenir molts problemes amb l’API doncs vaig estar treballant paral·lelament amb el Mario per aconseguir que funcionés i vam haver-li de dedicar moltes hores.

==== [aqua]#9.4.3. HECTOR#
Les incidències que he trobat per la meva part ha estat per part dels requisitsdel sistema, ja que no podia treballar molt a classe i no podia comprovar si la pantalla o l’aplicació funcionava correctament, això feia que despenges dels meus companys i no avancin per culpa meva, ja que no tenia el sistema que es requeria per fer aquest projecte.

La incidència del sistema ha sigut la incidència que més m’ha perjudicat perquè per no tenir els requisits de la màquina he anat molt atabalat a més que era un projecte curt i que al principi em va costar posar-me amb el projecte, ja que no entenia res. 

==== [aqua]#9.4.4. YAIZA#
Durant el projecte, he tingut diverses dificultats tècniques, sobretot per connectar el Frontend amb el Backend. Al principi, vaig voler evitar l’ús d’IA per demostrar que podia desenvolupar el projecte sense dependre d’això, però la falta de temps i els errors amb l’API em van obligar a buscar ajuda per no frenar l’equip. Vaig perdre dos dies intentant solucionar un problema i, finalment, vaig recórrer a suport extern per arribar a l’entrega.
Un dels principals entrebancs va ser el desplegable de categories, que vaig implementar de manera poc eficient en un principi. En comptes de connectar correctament l’entitat Categoria amb Videojoc, vaig afegir un camp extra per gestionar-les manualment, cosa que va generar errors i inconsistències que em van fer perdre molt de temps quan dies després vaig voler posar-me amb això.
També vaig tenir dificultats amb la pantalla de modificació. Al començament no sabia com abordar-la i la vaig haver de deixar per avançar en altres tasques. Quan la vaig reprendre, encara em donava molts problemes fins que, després de diversos intents, va acabar funcionant.

==== [aqua]#9.4.5. GRUP#
Grupalment, hem trobat un gran problema al llarg de tot el projecte que ens ha endarrerit molt. La principal incidència que hem trobat a escala grupal és amb les eines de treball, els requisits de sistema per a l’ús d’emuladors a l’Android Studio són molt exigents i no coincideixen amb els requisits de sistema mínims que se’ns van demanar de cara a tenir un portàtil per a poder començar el grau. Això ens ha portat a tenir dos portàtils en el nostre grup que no podien provar les funcionalitats que s’anaven fent. A més, feien els portàtils anar amb molt de lag i s’acabaven congelant tota l’estona. 