:hardbreaks:
== [aqua]#8. PLANIFICACIÓ I SEGUIMENT SETMANAL#
=== [red]#FALTA POR HACER#
//TODO: FALTA POR HACER
Enllaç al Trello grupal de gamedex: https://trello.com/invite/b/67935061f9febf9359af1e6c/ATTIed687fb1113b36c123fa5e384c0eb025D9BFC44F/gamedex


=== [aqua]#8.1. Sprint 1#

==== [aqua]#8.1.1. Tasques realitzades#

===== [aqua]#8.1.1.1. Hector#

** Afegir Categoria backend (1 hora)

** Modificar Categoria backend (1 hora)

** Eliminar Categoria backend (1 hora)

** Llistar Categoria backend (1 hora)

** Test CRUD Categoria backend (2 hores)

** Consulta Categoria backend (1 hora)

** Filtre Categoria backend (1 hora)

** Pantalla LlistaCategoria + AfegirCategoria frontend (15 hores)

** Detalls del TopBar frontend (1 hora)


===== [aqua]#8.1.1.2. Yaiza#

** Afegir Videojoc  (2 hores)

** Modificar Videojoc (1 hora)

** Eliminar Videojoc (30 minuts)

** Llistar Videojocs (30 minuts)

** Consultar Videojoc (1 hora)

** Filtre Videojoc (1 hora)

** Pantalla AfegirVideojoc + altres detalls (15h)


===== [aqua]#8.1.1.3. Anna#

** Afegir comentari: backend (3 hores)

** Llistar usuaris (sense filtres) backend (1 hora)

** Eliminar comentari backend (1 hora)

** Test comentarisLogica backend (2 hores)

** BottomNavBar frontend (3 hores)

** LoginPantalla frontend (6 hores)

** Estructura navegation frontend (3 hores)

===== [aqua]#8.1.1.4. Mario#

** Registre Usuari backend i pantalla(3 hores) 

** Modificar Usuari backend (1 hora) 

** Eliminar Usuari backend (1 hora) 

** Llistar Usuari backend (1 hora)

** Filtre Usuari backend (1 hora)

** Registre Admin + test crud Usuaris backend (1 hora)

** Preparar asciidocs per a tots els apartats de la memoria pendents (1h)

** Configuració d'api i bases d'api backend i frontend(20h)


==== [aqua]#8.1.2. Release notes#

** Afegir comentari: Anna (3 hores)

** Llistar usuaris (sense filtres) Anna (1 hora)

** Eliminar comentari: Anna (1 hora)

** Test comentarisLogica: Anna (2 hores)

** BottomNavBar: Anna (3 hores)

** LoginPantalla: Anna (6 hores)

** Estructura navegation: Anna (3 hores)

** Registre Usuari: Mario (3 hores) 

** Modificar Usuari: Mario (1 hora)

** Eliminar Usuari: Mario (1 hora)

** Llistar Usuari: Mario (1 hora)

** Filtre Usuari: Mario (1 hora)

** Registre Admin + test crud Usuaris: Mario (1 hora)

** Preparar asciidocs para todos los apartados de memoria pendientes: Mario (1h)

** Configuracion de api y bases de api: Mario i Anna (20h)

** Afegir Categoria: Héctor (1 hora)

** Modificar Categoria: Héctor (1 hora)

** Eliminar Categoria: Héctor (1 hora)

** Llistar Categoria: Héctor (1 hora)

** Test CRUD Categoria: Héctor (2 hores)

** Consulta Categoria: Héctor (1 hora)

** Filtre Categoria: Héctor (1 hora)

** Pantalla LlistaCategoria + AfegirCategoria: Héctor (15 hores)

** Detalls del TopBar: Héctor (1 hora)

** Afegir Videojoc: Yaiza (2 hores)

** Modificar Videojoc: Yaiza (1 hora)

** Eliminar Videojoc: Yaiza (30 minuts)

** Llistar Videojocs: Yaiza (30 minuts)

** Consultar Videojoc: Yaiza (1 hora)

** Filtre Videojoc: Yaiza (1 hora)

** Pantalla AfegirVideojoc + altres detalls: Yaiza (15h)


==== [aqua]#8.1.3. Incidències#

(Dilluns 10/02) L’Héctor, la Yaiza i l’Anna han estat molta estona intentant resoldre problemes amb l’Android Studio. Havíem de fer un pull de l’estructura i ens dónava molts problemes, començant pels “fetch” que no acabaven, documents creats al visual que no havíem creat nosaltres i que ens dónaven problemes per a poder fer el pull. A les 8:55, l’Anna havia pogut fer el pull, però l’IDE posava que “Kotlin index are corrupted” i no podia continuar. A les 9:10 hem decidit esborrar la carpeta “caches” motivats pel ChatGPT. A l’Anna li ha començat a funcionar l’Android Studio a les 9:29.

(Dilluns 10/02) A les 10:17 hem sapigut que havíem de crear tot el projecte de nou perquè havíem entès que havíem de fer servir la plantilla del Bottom Navigation. Sembla ser que és una versió antiga i que no ens serveix, i és ara que ho sabem. 


(Dimarts 11/02 - Dijous 13/02) Problemes amb l'api. Hem treballat mes de 15 hores a l'api i continua sin funcionar. No terminem de entre el funcionament de l'api i en demanar ajuda al professor nos ens ha pogut ajudar.

==== [aqua]#8.1.4. Analisis final#

===== [aqua]#8.1.4.1. Hector#

**Hores dedicades:**

Les hores que he dedicat ha sigut la següent:

Afegir Categoria (1 hora)
Modificar Categoria (1 hora)
Eliminar Categoria (1 hora)
Llistar Categoria (1 hora)
Test CRUD Categoria (2 hores)
Consulta Categoria (1 hora)
Filtre Categoria (1 hora)
Pantalla LlistaCategoria + AfegirCategoria (16 hores)
Detalls del TopBar (1 hora)
 
**Tasques realitzades:**

Les tasques que he realitzat han sigut:

Crear tot el CRUD del BackEnd de la part de Categoria.
També he creat els tests del CRUD per poder comprovar que funcionin bé i poder començar amb el FrontEnd.
I amb tot el CRUD creat he començat a fer les pantalles de Categoria, però de moment tan sols tinc dues creades, que són, LlistaCategoria i AfegirCategoria, en les pantalles també he fet les traduccions de String en strings.xml, d’anglès, català i espanyol.

**Aspectes positius del treball realitzat:**

M’he tret mitja part de la pantalla, però sento que encara me'n queda moltíssim, fent les pantalles he après bastant Kotlin i més que res m’està agradant la part de crear les pantalles, però sento que això no és res, encara queda moltíssim per fer. Això és el que sento jo, perquè no sabem bé com anem respecte al pes del projecte.

**Problemes trobats durant l’sprint:**

Un problema que he vist és que en tres setmanes amb els temes que tenim i amb les pràctiques en mig no tinc molt temps per poder, estudiar i posar-me a fer el projecte, perquè surto de les pràctiques a les 18 i arribo a les 19:00 a casa i no tinc temps per tot, llavors no sé com organitzar-me les hores, però això és problema meu. Per part de l’sprint és que no sé com fer res de l'API, però més que res no he començat, però pel següent sprint segur que tindre completat o començat, també tinc molts dubtes per part de les pantalles, perquè no sé com fer que es posin les dades de la base de dades en aquestes pantalles.

**Accions concretes per aplicar millores en els següents sprints:**

L'única millora que jo veig és que he d’anar més de pressa i fer més en casa, aquesta part és personal. Però per part de Grup crec que estem anant bé, però això depèn de com anem avançant perquè portem una setmana.


===== [aqua]#8.1.4.2. Yaiza#

**Hores dedicades:**

Les hores que he dedicat ha sigut la següent:

Afegir Videojoc  (2 hores)
Modificar Videojoc (1 hora)
Eliminar Videojoc (30 minuts)
Llistar Videojocs (30 minuts)
Consultar Videojoc (1 hora)
Filtre Videojoc (1 hora)
Pantalla AfegirVideojoc + altres detalls (15h)
Pantalla VisualitzarVideojoc (6h)
 
**Tasques realitzades:**

He creat tot el CRUD del BackEnd de la part de Videojocs i el filtre per consultar per ID. Quan ja he fet tota la part del CRUD, he començat a fer les pantalles de Videojoc. Fins ara tinc dues acabades, AfegirVideojoc i VisualitzarVideojoc. 

**Aspectes positius del treball realitzat:**

De cara al primer dia quan vam començar les pantalles, vaig començar amb molts dubtes i moltes dificultats a l'hora de plasmar les nostres idees, però a causa de prova i error, he anat avançant i m’he anat fent millor a android studio i kotlin, anant ara més ràpid amb les següents pantalles que hauré de fer.
Problemes trobats durant l’sprint:

L’únic que hem avançat han sigut les pantalles visualment. Tema connectar el Frontend amb el Backend, hem tingut molts dubtes, i en el meu cas per exemple, he de fer el llistat de videojocs, però com no tenim cap videojoc creat, tampoc sé com fer la pantalla sense afegir, diguem, les dades manualment a l’Android studio, i a causa d’estar pensant com fer o com no fer una pantalla, he tardat massa i estic anant molt més lenta del que m'agradaria.

**Accions concretes per aplicar millores en els següents sprints:**

Més que res suposo que hauríem d’intentar organitzar-nos millor i intentar fer les coses més ràpidament.


===== [aqua]#8.1.4.3. Anna#

**Hores dedicades:**
De base he dedicat unes 19 hores a fer les meves funcionalitats. A més he estat dedicant hores a organitzar el grup i a ajudar amb funcionalitats als meus companys, en total he dedicat unes 29 hores. 
 
**Tasques realitzades:**
En un principi jo m’encarregava de fer tot allò relacionat amb la biblioteca/comentaris, no obstant en ser una entitat que té relacions de dependència amb altres entitats, no m’ha sigut possible progressar molt. És per això que he fet els CRUD molt bàsics de comentari, i els seus test corresponents. També m’he encarregat de fer una plantilla al front end per a facilitar la implementació de la Bottom Navigation Bar en totes les pantalles i que fos funcional. Vaig començar la pantalla d’afegir comentari, però quan vaig adonar-me de què necessitava les entitats dels meus companys, em vaig posar a fer la pantalla de login. Vaig crear tota l’estructura de navegació per botons. Finalment, vaig estar ajudant el Mario a implementar l’api i comprovar que funcionés la creació d’un usuari, cosa que ens va portar al voltant de 20 hores, però sense això no podíem avançar gaire.

**Aspectes positius del treball realitzat:**
Em sento molt motivada a aprendre més sobre kotlin i android studio per als meus projectes personals. Però no estic molt contenta de la frustració que hem viscut aquesta setmana i, per tant, no puc trobar gaires aspectes positius. Per dir algun aspecte positiu, ara no veig tan difícil fer les pantalles, crec que és bastant intuïtiu.
Problemes trobats durant l’sprint:

Hem trobat molts problemes durant aquest Sprint. Primer de tot no teníem gaire clar res de conceptes tècnics i ens ha costat molt posar-nos a treballar. Crec que han estat massa coneixements nous per a un mateix projecte i ha estat molt frustrant. Quan ja havíem creat els dos projectes (front i back end), i havíem començat a treballar seguint les indicacions que s’havien estat donant a classe, vam haver de començar de nou el projecte del front end perquè no funcionava amb la plantilla que havíem de fer servir. Això ens va suposar un retard. A més a l’hora de fer l’api, com no teníem gaire clar com fer-la, vaig demanar al Mario que ell s’encarregués d’investigar mentre jo feia la implementació de la navegació, però donava molts errors i m’hi vaig posar amb ell a solucionar-ho en paral·lel, per tant, vam estar tots dos provant solucions a la vegada, cosa que ens va fer perdre encara més temps, com 20 hores. 

**Accions concretes per aplicar millores en els següents sprints:**

Ara que hem aconseguit que funcioni l’api, ens toca treballar a un ritme més ràpid, ja que hauríem tots de tenir clar com funcionen la majoria de les coses a fer.


===== [aqua]#8.1.4.4. Mario#

**Hores dedicades:**
He dedicat un aproximat de 29 hores a les meves funcionalitats, però la majoria de les hores han sigut dedicades a l’api i els problemes que ens donava. A més a més, he dedicat algunes hores extra per a ajudar a la resta del grup i per als moments en què havíem de parlar decisions grupals.
 
**Tasques realitzades:**
He començat dedicant-me principalment a les funcionalitats associades a l'usuari. Vaig començar per crear l'entitat d'usuari, l’enum UserType, el repository i la lògica pel CRUD, a més vaig afegir la pantalla de registre. Després vaig començar a intentar fer la implementació de l’api, vaig començar per intentar configurar-la i implementar-la però vaig trigar moltes hores, ja que no hi tenia prou coneixements. L’api donava molts errors i problemes en els quals he hagut d’invertir moltes hores.

**Aspectes positius del treball realitzat:**
Personalment, em costa trobar aspectes positius al treball d’aquesta setmana. Ha sigut molt agobiant i frustrant, ja que hem tingut molts problemes. Si haig de dir alguna cosa positiva és que, donada aquesta setmana de treball intensiu, a l'últim projecte tindre més facilitats per completar algunes coses.

**Problemes trobats durant l’sprint:**

Hem tingut molts problemes. Un dels problemes va ser una manca de comunicació amb el professorat que ens va fer haver de crear el projecte del frontend dues vegades, retardant molt el treball. A més, com que hem hagut d’adquirir molts coneixements en molt poc temps, tenim molts dubtes que impedeixen avançar amb velocitat. Sento que el professorat continua mancant en comunicació i, per tant, hi ha hagut diverses vegades en què he hagut de fer una mateixa funcionalitat o entitat més de tres vegades, ja que cada professor em deia una cosa distinta. Finalment, l’api no em va quedar molt clara i he trigat molt de temps en fer-la, ha sigut molt frustrant, perquè tampoc he rebut gaire ajuda quan l'he demanat.

**Accions concretes per aplicar millores en els següents sprints:**

Penso que als següents sprints haurem d’aprofitar els coneixements adquirits en aquest sprint per avançar molt més ràpid, ja que si no dupliquem o tripliquem la velocitat de treball no crec que puguem arribar a l'entrega final, i menys tenint en compte que haurem de reservar dies al mig del projecte per a estudiar per als exàmens.


=== [aqua]#8.2. Sprint 2#

==== [aqua]#8.2.1. Tasques realitzades#

===== [aqua]#8.2.1.1. Hector# 

** Configuració API Pantalla AddCategory (5 hores)

** Configuració API Pantalla ListCategory (5 hores)

** Configuració Imatges en AddCategory (7 hores)

** Creació de la pantalla ViewCategory (3 hores)

** Configuració API Pantalla ViewCategory (5 hores)

===== [aqua]#8.2.1.2. Yaiza#

** Creació Pantalla ListVideogames (3 hores) 

** Configuració api Pantalla AddGame + ViewGame + ListVideogame  (19 hores)

** Modificacions a les pantalles (2 hores)

===== [aqua]#8.2.1.3. Anna#

** Login (19 hores)

** Afegir videojoc a la biblioteca (2 hores)

** FOL (1 hora)

===== [aqua]#8.2.1.4. Mario#

** Imatges a registrar usuari (2 hores)

** Listar usuaris (10 hores)

** Perfil d'usuari (3 hores)

** Navegació de pantalles (2 hores)

==== [aqua]#8.2.2. Release notes#

** Imatges a registrar usuari (2 hores) Mario

** Listar usuaris (10 hores) Mario

** Perfil d'usuari (3 hores) Mario

** Navegació de pantalles (2 hores) Mario

** Creació Pantalla ListVideogames (3 hores) Yaiza

** Configuració api Pantalla AddGame + ViewGame + ListVideogame  (19 hores) Yaiza

** Modificacions a les pantalles (2 hores) Yaiza

** Configuració API Pantalla AddCategory (5 hores) Hector

** Configuració API Pantalla ListCategory (5 hores) Hector

** Configuració Imatges en AddCategory (7 hores) Hector

** Creació de la pantalla ViewCategory (3 hores) Hector

** Configuració API Pantalla ViewCategory (5 hores) Hector

** Login (19 hores) Anna

** Afegir videojoc a la biblioteca (2 hores) Anna

** FOL (1 hora) Anna


==== [aqua]#8.2.3. Incidències#
La principal incidència que hem tingut aquest sprint és que dels 4 membres del grup hi ha 2 que no poden fer ús de l'emulador del android studio. Hem descobert aquesta setmana que atès que la API només es pot utilitzar en local, ja que no està publicada en cap servidor, no es pot fer l'execució del android studio des del mòbil i, per tant, tot el testatge de funcionalitats i el treball en general s'ha vist afectat significativament.

==== [aqua]#8.2.4. Analisis final#

===== [aqua]#8.2.4.1. Hector#
**Hores dedicades:**

Configuració API Pantalla AddCategory (5 hores)
Configuració API Pantalla ListCategory (5 hores) 
Configuració Imatges en AddCategory (7 hores)
Creació de la pantalla ViewCategory (3 hores)
Configuració API Pantalla ViewCategory (5 hores)

**Tasques realitzades:**

Les tasques que he realitzat ha sigut la implementació de l’API i poder entendre com funciona aquesta part, ja que no l’entenc molt i l’he d’estudiar per poder tenir una nota decent en l’API. He estat bastant amb aquest part perquè el volia tenir tot bé, encara que no puc comprovar-lo amb aquest portàtil he pogut avançar molt això és el que crec jo. He afegit la part de l’API a les pantalles de AddCategory i ListCategory per poder comprovar que funcioni bé i l’he pogut acabar i funcionen bé les dues. He començat amb ViewCategory i de moment se guixo amb la implementació de la pantalla, ja que tinc l’API creat i em queda que funcioni. 

**Aspectes positius del treball realitzat:**

Ara que sé com funciona i com treballar amb l’API sento que baix molt més ràpid i podré acabar la part de Categoria en dos dies mínim, en si era perquè no entenia res de l’API i de la seva implementació, però ara que sé com funciona  ja no vaig tan atabalat.

**Problemes trobats durant l’sprint:**

Els primers problemes que he trobat ha sigut el tema de les imatges perquè no entenia res i tampoc com funcionava, però al Mario em va donar un cop de mà i em va explicar com funciona i ara no és un gran problema. També crec que un problema podrà ser el tema dels filtres, per aquest motiu l’estem deixant com l’última acció per fer.

**Accions concretes per aplicar millores en els següents sprints:**

Un aspecte a millorar és que he d’anar més de pressa, perquè no hi ha temps per tenir tot acabat per l’entrega final, llavors he de fer a casa per poder avançar més i poder tenir tot bé per l’entrega.


===== [aqua]#8.2.4.2. Yaiza#
**Hores dedicades:**

Creació Pantalla ListVideogames (3 hores) 
Configuració api Pantalla AddGame + ViewGame + ListVideogame  (19 hores)
Modificacions a les pantalles (2 hores)

**Tasques realitzades:**

Aquesta setmana he estat familiaritzant-me amb com fer la part de l'API i veure com funciona, llavors m’he estat molta estona al principi. He fet funcional la pantalla AddGames i ViewGames, he creat la pantalla de ListVideogames i també l'he fet funcional. Ara que ja està fet entre cometes el bàsic d’aquestes pantalles, intentaré fer la part d’afegir imatges i fer que en afegir una categoria al joc, sigui amb un desplegable, que és el que estic intentant ara.

**Aspectes positius del treball realitzat:**

Ara que entenc millor el tema de l’API ja no estic tan amoïnada com en un principi, he començat a veure una mica més clares les coses en haver començat a veure resultats de cara a veure les pantalles funcionals.

**Problemes trobats durant l’sprint:**

Tema grup no he vist cap problema, l’única cosa ha sigut més una mica en l'àmbit personal. Ja que fins ara, he estat intentant no utilitzar cap mena d'IA en tot el projecte, perquè volia que es veiés que no em calia dependre d’una eina així per fer coses per mi mateixa. La primera setmana no vaig utilitzar res, però com tenim poc temps, no tinc temps de posar-me a pensar com fer-ho jo absolutament tot sense haver d’utilitzar res. Llavors he hagut de dependre una mica aquesta setmana perquè tenia molts errors amb el tema de l'API i no trobava el perquè. Vaig estar 2 dies amb una mateixa cosa i vaig perdre molt de temps, llavors vaig haver d’utilitzar eines perquè si no no arribarem a l’entrega, i no vull que per una cosa que m’he ficat al cap, això em faci anar més lenta i això perjudiqui el meu grup.

**Accions concretes per aplicar millores en els següents sprints:**

No sabria que dir exactament, només sé que, personalment, he de fer alguna cosa per tenir present que he de fer i fer les coses pas a pas, perquè un problema que tinc és que vaig fent i vaig deixant les coses a mitges segons avanço, i hauria de, començar, acabar i següent. Intentaré fer-ho per l’últim sprint.



===== [aqua]#8.2.4.3. Anna#
**Hores dedicades:**
Login (19 hores)
Afegir videojoc a la biblioteca (2 hores)
FOL (1 hora)


Aquesta setmana he treballat unes 24 hores. En funcionalitats com a tal he estat unes 21 hores i en organització temporal i git entre una i dues hores. A més, cal comptar l’hora de la classe de FOL, on la professora ens va estar donant instruccions sobre la nova tasca a realitzar.

**Tasques realitzades:**
Aquesta setmana he estat dedicant-me a fer funcional el login tant al front com en el back end. A més també he arreglat una de les meves pantalles que m’estava donant molts problemes.

**Aspectes positius del treball realitzat:**
L’única cosa que veig positiva d’aquest sprint és que finalment tenim una aplicació funcional des del principi. El fet que ara puguis registrar-te i iniciar sessió de manera funcional, em fa sentir realitzada i motivada.

**Problemes trobats durant l’sprint:**
Personalment, no he estat molt productiva aquesta setmana per problemes personals i m’ha costat molt superar els obstacles que estava trobant mentre feia el login. Tot i que entenia com havia de fer perquè funcionés, no era capaç de solucionar tots els problemes que trobava. Vaig haver de recórrer molt a la IA i tot i això vaig entrar en un bucle provant solucions. Finalment, vaig decidir esborrar tot i tornar-ho a fer, cosa que em va endarrerir moltíssim. 
A més, en tenir l’entitat de biblioteca que depèn d’altres entitats, tot i tenir fetes algunes de les pantalles, no puc implementar la funcionalitat del back end i de l’api. Per tant, la setmana vinent tindré molta feina. 

**Accions concretes per aplicar millores en els següents sprints:**
Hauré de fer molta feina a casa, ja que el portàtil em funciona bastant malament per a provar les funcionalitats amb l’emulador, cosa que amb el mòbil no em passava. 
També he d’intentar no entrar en bucle, si no veig clara una solució després d’una mica de temps, he de tornar a començar o buscar una alternativa.


===== [aqua]#8.2.4.4. Mario#
**Hores dedicades:**
Aquest sprint li he pogut dedicar menys hores, ja que he tingut problemes de salut que m'han fet no estar tant de temps a classe i no poder fer més a casa. Tot i això he fet aproximadament un total de 17 hores entre totes les meves funcionalitats.

**Tasques realitzades:**

** Imatges a registrar usuari (2 hores)

** Llistar usuaris (10 hores)

** Perfil d'usuari (3 hores)

** Navegació de pantalles (2 hores)

**Aspectes positius del treball realitzat:**
He aconseguit aprendre a fer la gestió d'imatges (que l'usuari pugui pujar una imatge, guardar-la en la base de dades i poder-la recuperar posteriorment) malgrat totes les dificultats que m'he trobat en el procés. En haver aconseguit això i altres petits avanços que hem donat aquesta setmana ens faciliten molt el treball per a l'última setmana en la qual tot hauria d'anar més fluid.

**Problemes trobats durant l’sprint:**
Les imatges m'han pres massa temps, per la qual cosa, entre això i els problemes de salut, no he pogut fer grans avanços. He trobat moltes dificultats i no he sabut gestionar correctament el meu treball

**Accions concretes per aplicar millores en els següents sprints:**
Aquesta setmana no trobo moltes coses a millorar, ja que he fet molta feina individual i he estat menys hores amb el meu grup en classe.



=== [aqua]#8.3. Sprint 3#

==== [aqua]#8.3.1. Tasques realitzades#

===== [aqua]#8.3.1.1. Hector#

** Pantalla ViewCategory (6 hores)

** Eliminar Category (2 hores)

** Filtre Category en la Llista (4 hores i no esta acabada)

** Implementació de la Logica al BackEnd (1 hora)

** Implementació de Retrofit, APIrest i ViewModel (1 hora)

** UI Pantalla Modify (4 hores) i no em surt res no se com fer aquesta part i he avançat una mica a casa i tampoc, no se com fer aquesta part.

===== [aqua]#8.3.1.2. Yaiza#

** Desplegable Categoria (6h)

** Afegir imatge (3h)

** Camps buits (2h)

** Botons afegir i visualitzar videojocs funcionals (1h)

** Visualitzar imatge (2h)

** Botó validar jocs afegits (30 min)

** Visualitzar imatge (30 min)

** Funcionalitat esborrar i botó d’esborrar funcional (3h)

** Mirat per sobre com fer pantalla Modificar Videojocs (1h)

** Pantalla Llistar videojocs no validats (ListInactiveGames) (3h)

===== [aqua]#8.3.1.3. Anna#

** Correcció de strings i traducció (1 hora i mitja)

** Afegir videojoc a la biblioteca (13 hores)

** Recuperar contrasenya (9 hores)

** Consultar biblioteca personal (5 hores)

===== [aqua]#8.3.1.4. Mario#

** Registre admin (1 hora)

** Millores en el backend (2 hores)

** Modificar Usuari (15 hores)

** Perfil d’usuari (1 hora)

** validar usuaris (1 hora)

** Eliminar usuari (30 minuts)

** Solució d’errors generales (3 hores i mitja)

==== [aqua]#8.3.2. Release notes#

** Pantalla ViewCategory (6 hores)

** Eliminar Category (2 hores)

** Implementació de la Logica al BackEnd (1 hora)

** Implementació de Retrofit, APIrest i ViewModel (1 hora)

** Desplegable Categoria (6h)

** Afegir imatge (3h)

** Camps buits (2h)

** Botons afegir i visualitzar videojocs funcionals (1h)

** Visualitzar imatge (2h)

** Botó validar jocs afegits (30 min)

** Visualitzar imatge (30 min)

** Funcionalitat esborrar i botó d’esborrar funcional (3h)

** Mirat per sobre com fer pantalla Modificar Videojocs (1h)

** Pantalla Llistar videojocs no validats (ListInactiveGames) (3h)

** Correcció de strings i traducció (1 hora i mitja)

** Afegir videojoc a la biblioteca (13 hores)

** Recuperar contrasenya (9 hores)

** Consultar biblioteca personal (5 hores)

** Registre admin (1 hora)

** Millores en el backend (2 hores)

** Modificar Usuari (15 hores)

** Perfil d’usuari (1 hora)

** validar usuaris (1 hora)

** Eliminar usuari (30 minuts)

** Solució d’errors generales (3 hores i mitja)


==== [aqua]#8.3.3. Incidències#

==== [aqua]#8.3.4. Analisis final#

===== [aqua]#8.3.4.1. Hector#
**Hores dedicades:**

** Pantalla ViewCategory (6 hores)

** Eliminar Category (2 hores)

** Filtre Category en la Llista (4 hores i no esta acabada)

Modificar Category:

** Implementació de la Logica al BackEnd (1 hora)

** Implementació de Retrofit, APIrest i ViewModel (1 hora)

** UI Pantalla Modify (4 hores) i no em surt res no se com fer aquesta part i he avançat una mica a casa i tampoc, no se com fer aquesta part.

**Tasques realitzades:**

En aquest Sprint el que he fet ha sigut acabar la part de ViewCatgory i acabar el que hem faltat, però he tingut molts problemes a l’hora de crear la pantalla del ViewCategory, no sabia com fer-la i em donava molts problemes per la part de mostrar la informació d’una categoria i tan sols em mostrava la pantalla buida i vaig intentar de tot, però va ser una cosa molt absurda que va ser l’URL, ja que no estava igual que en el BackEnd i vaig modificar de tot. També vaig fer la part d’eliminar categoria i vaig fer que el botó tan sols la pugui veure l’administrador i no vaig tenir cap problema el vaig posar dintre d’un if amb un currentuser i no tenia cap complicació.

Després de fer la part d’eliminar vaig començar per la de modificar vaig fer tota la part lògica, però després per mostrar la informació i poder fer-la editable em dona molts problemes i vaig estar molta estona i vaig decidir començar amb filtre, ja que volia descansar de fer la part de Modificar.

Encara estic fent la part de filtrar, tinc la part del SearchBar, però no em funciona del tot, he de continuar aquesta part.

**Aspectes positius del treball realitzat:**

Que em funciona el ViewModel i que eliminar està bé i de moment no estic anant tan malament, però sento que no he anat amb bon ritme, ja que estic trigant molt a fer les coses i quan no em surt una cosa no paro i si no aconsegueixo el que estic fent em frustro i em bloquejo.




**Problemes trobats durant l’sprint:**

El problema que he trobat durant aquest sprint és que trigo molt a fer les coses i com que no puc comprovar que funciona bé per al meu ordinador, trigo molt a veure si funciona i que és el que està malament, llavors depenc dels meus companys en tota l’estona i si he de comprovar el meu codi el company que em deixa el seu ordinador està una estona sense fer res. Un altre problema és que quan he començat amb modificar he estat molta estona intentant que funcioni i he perdut molt de temps, quan podria haver començat per una altra cosa.

**Accions concretes per aplicar millores en els següents sprints:**

De cara al següent sprint hem de tenir tot acabat a sí que he de posar-me les piles i fer que funcioni tot bé i funcional.


===== [aqua]#8.3.4.2. Yaiza#

**Hores dedicades:**

Pantalla Creació de videojocs (AddGames) 

** Desplegable Categoria (6h)

** Afegir imatge (3h)

** Camps buits (2h)

Pantalla llistar videojocs (ListVideogames)

** Botons afegir i visualitzar videojocs funcionals (1h)

** Visualitzar imatge (2h)

** Botó validar jocs afegits (30 min)

Pantalla Consultar videojoc (ViewGames)

** Visualitzar imatge (30 min)

** Funcionalitat esborrar i botó d’esborrar funcional (3h)

** Mirat per sobre com fer pantalla Modificar Videojocs (1h)

** Pantalla Llistar videojocs no validats (ListInactiveGames) (3h)

**Tasques realitzades:**

Durant aquest sprint m’he dedicat a anar acabant petites coses que havia deixat per aquest sprint. A la pantalla d’Afegir Videojocs, he fet un desplegable pel camp de categoria, perquè agafi les categories existents a l’entitat de Categoria. He fet que la imatge es pugui afegir a la base de dades i es guardi i he fet que els camps a l'hora de crear un joc, si algun està buit, no deixi guardar. 
A la de llistar, he fet que tant el botó d’afegir un videojoc com el de visualitzar siguin funcionals i naveguin a la pantalla que pertoqui. Ara que ja he fet que la imatge es guardi, he estat intentant que la imatge es visualitzés per cada joc llistat i he afegit el botó que serà per validar els jocs afegits, encara no navega perquè la pantalla de validar encara no està feta.
A la pantalla de visualitzar, he fet que es visualitzi la imatge, que com ja ho havia fet abans a la de llistar, l'he fet més ràpidament i finalment, he estat afegint tota la part d’esborrar i he fet que el botó d’esborrar el videojoc sigui funcional.
Això són les coses funcionals que he estat fent aquesta setmana, després he mirat una mica per sobre com fer les pantalles de modificar i validar, però encarà no estan.

**Aspectes positius del treball realitzat:**
Aquesta setmana m’he fet un llistat de totes les coses que tinc pendents i he valorat quines podia fer més ràpidament o quines eren més necessàries per continuar i treure coses de sobre. Això ha fet que hagi vist el que he anat avançant i tot i que siguin coses petites, sento que el ritme no ha estat gens malament.

**Problemes trobats durant l’sprint:**
A l’hora de fer el desplegable de categoria m’he estat molt de temps, que mirant enrere, podria haver-me estalviat si hagués posat ben connectada l’entitat de categoria a videojoc en comptes d’utilitzar un camp extra que tenia posat a la pantalla per afegir les categories manualment. Com no vaig pensar de cara a futur, ara m’he estat batallant bastant perquè tota l’estona hi havia incongruències, perquè ho agafava d’altre lloc que no era, o sortia null perquè resulta que havia posat altre nom… I era una cosa amb la qual vaig estar donant voltes quan, si ho hagués planejat bé des d’un principi, m’ho hauria tret de sobre molt més ràpid. Una altra cosa ha sigut quan he intentat començar a fer la pantalla de modificar i he vist que no sabia per on començar i com fer-la, llavor he intentat fer altres coses i en altre moment ja començaria a fer-la. La resta de coses les he anat resolent més de pressa i no ho veig tant problema, el que més problema m’ha donat aquesta setmana diria que ha sigut això del desplegable.

**Accions concretes per aplicar millores en els següents sprints:**
Ja de cara al següent projecte, el que hauria de fer seria plantejar-me molt millor que he de fer, com ho he de fer, i més o menys plantejar quant de temps trigaria aproximadament en cada cosa, per saber que coses hauria de prioritzar i quines serien més importants i es necessitin fetes per altres coses. Ja que he vist que he anat fent coses que he hagut d’anar deixant a meitat perquè no podia fer-les si no tenia altra cosa que no tenia feta.

===== [aqua]#8.3.4.3. Anna#
**Hores dedicades:**

He dedicat unes 33 hores aquest Sprint. A més de les tasques realitzades llistades al Release notes, també he dedicat 3 hores a les feines de FOL i una hora a organització. FALTA EL JUEVES!

**Tasques realitzades:**

Correcció de strings i traducció (1 hora i mitja)
Afegir videojoc a la biblioteca (13 hores)
Recuperar contrasenya (9 hores)
Consultar biblioteca personal (5 hores)

**Aspectes positius del treball realitzat:**

En poder treballar a casa a partir del dimecres per la tarda, he pogut avançar molt més ràpid les funcionalitats. Ja tenim la navegació molt avançada i per tant es veu una bona feina.

**Problemes trobats durant l’sprint:**

Aquest sprint he estat treballant més a casa que a l’institut perquè el meu ordinador es laggeja i es congela quan faig servir l’emulador de l’Android Studio, per tant els primers dies d’aquest sprint vaig perdre molt de temps. Em vaig plantejar no venir a classe i quedar-me a casa treballant a la torre, però per por a necessitar les hores, no ho he fet. 

**Accions concretes per aplicar millores en els següents sprints:**

De cara a l’entrega hem de treballar molt. No crec que hi hagi que millorar res. 


===== [aqua]#8.3.4.4. Mario#

**Hores dedicades:**

Aquest sprint he dedicat al voltant de 26 hores de treball a les meves funcionalitats i a la solució d’errors generals que anava trobant a l'aplicació així com ajudar als meus companys amb les seves funcionalitats si trobaven problemes.

**Tasques realitzades:**

** Registre admin (1 hora)

** Millores en el backend (2 hores)

** Modificar Usuari (15 hores)

** Perfil d’usuari (1 hora)

** validar usuaris (1 hora)

** Eliminar usuari (30 minuts)

** Solució d’errors generales (3 hores i mitja)

**Aspectes positius del treball realitzat:**

He trobat moltes dificultats durant aquest sprint i he sigut capaç de superar-les totes amb poca ajuda. He trigat una mica més del que esperava en completar les funcionalitats que tenia pensades, però el fet d’haver superat tantes dificultats m’agrada.

**Problemes trobats durant l’sprint:**

He trobat moltes dificultats amb modificar usuaris, sobretot amb les imatges, ja que era un sistema molt complex. A més he tingut dificultats amb algunes de les solucions dels problemes com per exemple que la topbar no actualitzava correctament la imatge d’usuari quan aquesta era modificada.

**Accions concretes per aplicar millores en els següents sprints:**

Com sempre passa, penso que de cara al següent projecte haurem de treballar més de pressa i d’organitzar-nos millor. De cara a l’entrega final ens queda molta feina d’implementació a més de fer asciidocs, feina de fol i el vídeo, no sé si arribarem a tot.

