:hardbreaks:
== [aqua]#8. PLANIFICACIÓ I SEGUIMENT SETMANAL#
=== [red]#FALTA POR HACER#
//TODO: FALTA POR HACER
Enllaç al Trello grupal de gamedex: https://trello.com/invite/b/67935061f9febf9359af1e6c/ATTIed687fb1113b36c123fa5e384c0eb025D9BFC44F/gamedex


=== [aqua]#8.1. Sprint 1#

==== [aqua]#8.1.1. Tasques realitzades#

===== [aqua]#8.1.1.1. Hector#

** Afegir Categoria backend (1 hora)

** Modificar Categoria backend (1 hora)

** Eliminar Categoria backend (1 hora)

** Llistar Categoria backend (1 hora)

** Test CRUD Categoria backend (2 hores)

** Consulta Categoria backend (1 hora)

** Filtre Categoria backend (1 hora)

** Pantalla LlistaCategoria + AfegirCategoria frontend (15 hores)

** Detalls del TopBar frontend (1 hora)


===== [aqua]#8.1.1.2. Yaiza#

** Afegir Videojoc  (2 hores)

** Modificar Videojoc (1 hora)

** Eliminar Videojoc (30 minuts)

** Llistar Videojocs (30 minuts)

** Consultar Videojoc (1 hora)

** Filtre Videojoc (1 hora)

** Pantalla AfegirVideojoc + altres detalls (15h)


===== [aqua]#8.1.1.3. Anna#

** Afegir comentari: backend (3 hores)

** Llistar usuaris (sense filtres) backend (1 hora)

** Eliminar comentari backend (1 hora)

** Test comentarisLogica backend (2 hores)

** BottomNavBar frontend (3 hores)

** LoginPantalla frontend (6 hores)

** Estructura navegation frontend (3 hores)

===== [aqua]#8.1.1.4. Mario#

** Registre Usuari backend i pantalla(3 hores) 

** Modificar Usuari backend (1 hora) 

** Eliminar Usuari backend (1 hora) 

** Llistar Usuari backend (1 hora)

** Filtre Usuari backend (1 hora)

** Registre Admin + test crud Usuaris backend (1 hora)

** Preparar asciidocs per a tots els apartats de la memoria pendents (1h)

** Configuració d'api i bases d'api backend i frontend(20h)


==== [aqua]#8.1.2. Release notes#

** Afegir comentari: Anna (3 hores)

** Llistar usuaris (sense filtres) Anna (1 hora)

** Eliminar comentari: Anna (1 hora)

** Test comentarisLogica: Anna (2 hores)

** BottomNavBar: Anna (3 hores)

** LoginPantalla: Anna (6 hores)

** Estructura navegation: Anna (3 hores)

** Registre Usuari: Mario (3 hores) 

** Modificar Usuari: Mario (1 hora)

** Eliminar Usuari: Mario (1 hora)

** Llistar Usuari: Mario (1 hora)

** Filtre Usuari: Mario (1 hora)

** Registre Admin + test crud Usuaris: Mario (1 hora)

** Preparar asciidocs para todos los apartados de memoria pendientes: Mario (1h)

** Configuracion de api y bases de api: Mario i Anna (20h)

** Afegir Categoria: Héctor (1 hora)

** Modificar Categoria: Héctor (1 hora)

** Eliminar Categoria: Héctor (1 hora)

** Llistar Categoria: Héctor (1 hora)

** Test CRUD Categoria: Héctor (2 hores)

** Consulta Categoria: Héctor (1 hora)

** Filtre Categoria: Héctor (1 hora)

** Pantalla LlistaCategoria + AfegirCategoria: Héctor (15 hores)

** Detalls del TopBar: Héctor (1 hora)

** Afegir Videojoc: Yaiza (2 hores)

** Modificar Videojoc: Yaiza (1 hora)

** Eliminar Videojoc: Yaiza (30 minuts)

** Llistar Videojocs: Yaiza (30 minuts)

** Consultar Videojoc: Yaiza (1 hora)

** Filtre Videojoc: Yaiza (1 hora)

** Pantalla AfegirVideojoc + altres detalls: Yaiza (15h)


==== [aqua]#8.1.3. Incidències#

(Dilluns 10/02) L’Héctor, la Yaiza i l’Anna han estat molta estona intentant resoldre problemes amb l’Android Studio. Havíem de fer un pull de l’estructura i ens dónava molts problemes, començant pels “fetch” que no acabaven, documents creats al visual que no havíem creat nosaltres i que ens dónaven problemes per a poder fer el pull. A les 8:55, l’Anna havia pogut fer el pull, però l’IDE posava que “Kotlin index are corrupted” i no podia continuar. A les 9:10 hem decidit esborrar la carpeta “caches” motivats pel ChatGPT. A l’Anna li ha començat a funcionar l’Android Studio a les 9:29.

(Dilluns 10/02) A les 10:17 hem sapigut que havíem de crear tot el projecte de nou perquè havíem entès que havíem de fer servir la plantilla del Bottom Navigation. Sembla ser que és una versió antiga i que no ens serveix, i és ara que ho sabem. 


(Dimarts 11/02 - Dijous 13/02) Problemes amb l'api. Hem treballat mes de 15 hores a l'api i continua sin funcionar. No terminem de entre el funcionament de l'api i en demanar ajuda al professor nos ens ha pogut ajudar.

==== [aqua]#8.1.4. Analisis final#

===== [aqua]#8.1.4.1. Hector#

**Hores dedicades:**

Les hores que he dedicat ha sigut la següent:

Afegir Categoria (1 hora)
Modificar Categoria (1 hora)
Eliminar Categoria (1 hora)
Llistar Categoria (1 hora)
Test CRUD Categoria (2 hores)
Consulta Categoria (1 hora)
Filtre Categoria (1 hora)
Pantalla LlistaCategoria + AfegirCategoria (16 hores)
Detalls del TopBar (1 hora)
 
**Tasques realitzades:**

Les tasques que he realitzat han sigut:

Crear tot el CRUD del BackEnd de la part de Categoria.
També he creat els tests del CRUD per poder comprovar que funcionin bé i poder començar amb el FrontEnd.
I amb tot el CRUD creat he començat a fer les pantalles de Categoria, però de moment tan sols tinc dues creades, que són, LlistaCategoria i AfegirCategoria, en les pantalles també he fet les traduccions de String en strings.xml, d’anglès, català i espanyol.

**Aspectes positius del treball realitzat:**

M’he tret mitja part de la pantalla, però sento que encara me'n queda moltíssim, fent les pantalles he après bastant Kotlin i més que res m’està agradant la part de crear les pantalles, però sento que això no és res, encara queda moltíssim per fer. Això és el que sento jo, perquè no sabem bé com anem respecte al pes del projecte.

**Problemes trobats durant l’sprint:**

Un problema que he vist és que en tres setmanes amb els temes que tenim i amb les pràctiques en mig no tinc molt temps per poder, estudiar i posar-me a fer el projecte, perquè surto de les pràctiques a les 18 i arribo a les 19:00 a casa i no tinc temps per tot, llavors no sé com organitzar-me les hores, però això és problema meu. Per part de l’sprint és que no sé com fer res de l'API, però més que res no he començat, però pel següent sprint segur que tindre completat o començat, també tinc molts dubtes per part de les pantalles, perquè no sé com fer que es posin les dades de la base de dades en aquestes pantalles.

**Accions concretes per aplicar millores en els següents sprints:**

L'única millora que jo veig és que he d’anar més de pressa i fer més en casa, aquesta part és personal. Però per part de Grup crec que estem anant bé, però això depèn de com anem avançant perquè portem una setmana.


===== [aqua]#8.1.4.2. Yaiza#

**Hores dedicades:**

Les hores que he dedicat ha sigut la següent:

Afegir Videojoc  (2 hores)
Modificar Videojoc (1 hora)
Eliminar Videojoc (30 minuts)
Llistar Videojocs (30 minuts)
Consultar Videojoc (1 hora)
Filtre Videojoc (1 hora)
Pantalla AfegirVideojoc + altres detalls (15h)
Pantalla VisualitzarVideojoc (6h)
 
**Tasques realitzades:**

He creat tot el CRUD del BackEnd de la part de Videojocs i el filtre per consultar per ID. Quan ja he fet tota la part del CRUD, he començat a fer les pantalles de Videojoc. Fins ara tinc dues acabades, AfegirVideojoc i VisualitzarVideojoc. 

**Aspectes positius del treball realitzat:**

De cara al primer dia quan vam començar les pantalles, vaig començar amb molts dubtes i moltes dificultats a l'hora de plasmar les nostres idees, però a causa de prova i error, he anat avançant i m’he anat fent millor a android studio i kotlin, anant ara més ràpid amb les següents pantalles que hauré de fer.
Problemes trobats durant l’sprint:

L’únic que hem avançat han sigut les pantalles visualment. Tema connectar el Frontend amb el Backend, hem tingut molts dubtes, i en el meu cas per exemple, he de fer el llistat de videojocs, però com no tenim cap videojoc creat, tampoc sé com fer la pantalla sense afegir, diguem, les dades manualment a l’Android studio, i a causa d’estar pensant com fer o com no fer una pantalla, he tardat massa i estic anant molt més lenta del que m'agradaria.

**Accions concretes per aplicar millores en els següents sprints:**

Més que res suposo que hauríem d’intentar organitzar-nos millor i intentar fer les coses més ràpidament.


===== [aqua]#8.1.4.3. Anna#

**Hores dedicades:**
De base he dedicat unes 19 hores a fer les meves funcionalitats. A més he estat dedicant hores a organitzar el grup i a ajudar amb funcionalitats als meus companys, en total he dedicat unes 29 hores. 
 
**Tasques realitzades:**
En un principi jo m’encarregava de fer tot allò relacionat amb la biblioteca/comentaris, no obstant en ser una entitat que té relacions de dependència amb altres entitats, no m’ha sigut possible progressar molt. És per això que he fet els CRUD molt bàsics de comentari, i els seus test corresponents. També m’he encarregat de fer una plantilla al front end per a facilitar la implementació de la Bottom Navigation Bar en totes les pantalles i que fos funcional. Vaig començar la pantalla d’afegir comentari, però quan vaig adonar-me de què necessitava les entitats dels meus companys, em vaig posar a fer la pantalla de login. Vaig crear tota l’estructura de navegació per botons. Finalment, vaig estar ajudant el Mario a implementar l’api i comprovar que funcionés la creació d’un usuari, cosa que ens va portar al voltant de 20 hores, però sense això no podíem avançar gaire.

**Aspectes positius del treball realitzat:**
Em sento molt motivada a aprendre més sobre kotlin i android studio per als meus projectes personals. Però no estic molt contenta de la frustració que hem viscut aquesta setmana i, per tant, no puc trobar gaires aspectes positius. Per dir algun aspecte positiu, ara no veig tan difícil fer les pantalles, crec que és bastant intuïtiu.
Problemes trobats durant l’sprint:

Hem trobat molts problemes durant aquest Sprint. Primer de tot no teníem gaire clar res de conceptes tècnics i ens ha costat molt posar-nos a treballar. Crec que han estat massa coneixements nous per a un mateix projecte i ha estat molt frustrant. Quan ja havíem creat els dos projectes (front i back end), i havíem començat a treballar seguint les indicacions que s’havien estat donant a classe, vam haver de començar de nou el projecte del front end perquè no funcionava amb la plantilla que havíem de fer servir. Això ens va suposar un retard. A més a l’hora de fer l’api, com no teníem gaire clar com fer-la, vaig demanar al Mario que ell s’encarregués d’investigar mentre jo feia la implementació de la navegació, però donava molts errors i m’hi vaig posar amb ell a solucionar-ho en paral·lel, per tant, vam estar tots dos provant solucions a la vegada, cosa que ens va fer perdre encara més temps, com 20 hores. 

**Accions concretes per aplicar millores en els següents sprints:**

Ara que hem aconseguit que funcioni l’api, ens toca treballar a un ritme més ràpid, ja que hauríem tots de tenir clar com funcionen la majoria de les coses a fer.


===== [aqua]#8.1.4.4. Mario#

**Hores dedicades:**
He dedicat un aproximat de 29 hores a les meves funcionalitats, però la majoria de les hores han sigut dedicades a l’api i els problemes que ens donava. A més a més, he dedicat algunes hores extra per a ajudar a la resta del grup i per als moments en què havíem de parlar decisions grupals.
 
**Tasques realitzades:**
He començat dedicant-me principalment a les funcionalitats associades a l'usuari. Vaig començar per crear l'entitat d'usuari, l’enum UserType, el repository i la lògica pel CRUD, a més vaig afegir la pantalla de registre. Després vaig començar a intentar fer la implementació de l’api, vaig començar per intentar configurar-la i implementar-la però vaig trigar moltes hores, ja que no hi tenia prou coneixements. L’api donava molts errors i problemes en els quals he hagut d’invertir moltes hores.

**Aspectes positius del treball realitzat:**
Personalment, em costa trobar aspectes positius al treball d’aquesta setmana. Ha sigut molt agobiant i frustrant, ja que hem tingut molts problemes. Si haig de dir alguna cosa positiva és que, donada aquesta setmana de treball intensiu, a l'últim projecte tindre més facilitats per completar algunes coses.

**Problemes trobats durant l’sprint:**

Hem tingut molts problemes. Un dels problemes va ser una manca de comunicació amb el professorat que ens va fer haver de crear el projecte del frontend dues vegades, retardant molt el treball. A més, com que hem hagut d’adquirir molts coneixements en molt poc temps, tenim molts dubtes que impedeixen avançar amb velocitat. Sento que el professorat continua mancant en comunicació i, per tant, hi ha hagut diverses vegades en què he hagut de fer una mateixa funcionalitat o entitat més de tres vegades, ja que cada professor em deia una cosa distinta. Finalment, l’api no em va quedar molt clara i he trigat molt de temps en fer-la, ha sigut molt frustrant, perquè tampoc he rebut gaire ajuda quan l'he demanat.

**Accions concretes per aplicar millores en els següents sprints:**

Penso que als següents sprints haurem d’aprofitar els coneixements adquirits en aquest sprint per avançar molt més ràpid, ja que si no dupliquem o tripliquem la velocitat de treball no crec que puguem arribar a l'entrega final, i menys tenint en compte que haurem de reservar dies al mig del projecte per a estudiar per als exàmens.
